spring:
  datasource:
    url: jdbc:mysql://192.168.65.128:3306/book_store?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: mysql_jxNrWx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10        # 最大连接数
      minimum-idle: 5              # 最小空闲连接数
      idle-timeout: 30000          # 空闲连接超时时间（毫秒）
      connection-timeout: 30000     # 连接超时时间（毫秒）
      max-lifetime: 1800000        # 连接最大生命周期（毫秒)